In [1]:
import pandas as pd

In [2]:
data = {
    'SP': [104.1853528, 105.4612635, 105.4612635, 113.4612635, 104.4612635, 113.1853528, 105.4612635, 102.5985128, 102.5985128, 115.6452041, 111.1853528, 117.5985128, 122.1050553, 111.1853528, 108.1853528, 111.1853528, 114.3692933, 117.5985128, 114.3692933, 118.4729364, 119.1050553, 110.8408174, 120.2889958, 113.8291446, 119.1853528, 114.5985128, 120.7605199, 119.1050553, 99.56490661, 121.8408174, 113.4846092, 112.2889958, 119.9211148, 121.3926389, 111.2889958, 115.0130851, 114.0933825, 116.909442, 116.909442, 128.4612635, 116.3926389, 115.7488471, 117.4612635, 114.0933825, 114.3809661, 117.1050553, 118.2086984, 116.4729364, 127.909442, 118.2889958, 118.2889958, 118.2889958, 120.4043117, 143.3926389, 135.3926389, 126.4043117, 110.4612635, 118.2889958, 112.6452041, 115.5765794, 130.2086984, 117.6685497, 126.0481035, 125.3123415, 128.128401, 126.5985128, 132.4846092, 133.6802225, 133.3123415, 158.3006687, 164.5985128, 133.4159845, 133.1400738, 124.7152409, 121.864163, 132.864163, 169.5985128, 150.5765794, 151.5985128, 167.9444604, 139.8408174],
    'WT': [28.7620589, 30.46683298, 30.19359657, 30.63211391, 29.88914864, 29.59176832, 30.30847957, 15.84775807, 16.35948352, 30.92015417, 29.36334142, 15.75353468, 32.81359241, 29.3784363, 29.34727902, 29.60452658, 29.5357836, 16.19412154, 29.92939368, 33.51697417, 32.32464971, 34.90821127, 32.6758277, 31.83712236, 28.78172789, 16.04317492, 38.06282335, 32.83506939, 34.4832075, 35.54935984, 37.04235003, 33.23436141, 31.38004084, 37.57328965, 32.701644, 31.9112234, 28.75400008, 27.87991549, 28.63050247, 30.11543403, 37.39252442, 35.02717556, 30.52742698, 28.34397592, 33.07863163, 32.62191589, 36.49861738, 33.91005598, 28.07059654, 33.45847152, 33.21395395, 33.43671117, 40.39816357, 37.62069475, 37.25439197, 40.58906845, 30.14754329, 32.73451818, 30.61528334, 37.66287367, 36.88815313, 37.86041143, 43.3909885, 40.72283115, 40.15948186, 15.71285853, 37.97995604, 41.57397476, 40.47204238, 37.14173328, 15.82306042, 44.01313857, 43.35312292, 52.99775236, 42.61869847, 42.77821864, 16.13294744, 37.92311321, 15.76962542, 39.42309899, 34.94861469]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
statistics = df.describe()
print(statistics)

               SP         WT
count   81.000000  81.000000
mean   121.540272  32.412577
std     14.181432   7.492813
min     99.564907  15.712859
25%    113.829145  29.591768
50%    118.208698  32.734518
75%    126.404312  37.392524
max    169.598513  52.997752